# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05eff69fa834eaeb6b5cab7b4c0276a3"
name = "Performance Styling Collab"
application_url = "https://performance-styling-shopify-production.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://performance-styling-shopify-production.onrender.com/auth/callback" ]

[app_proxy]
url = "/apps/collab"
prefix = "apps"
subpath = "collab"
